package com.financeplatform.recurring.service;

import com.financeplatform.account.service.AccountService;
import com.financeplatform.common.exception.InvalidRequestException;
import com.financeplatform.common.exception.ResourceNotFoundException;
import com.financeplatform.recurring.dto.RecurringTransactionRequest;
import com.financeplatform.recurring.dto.RecurringTransactionResponse;
import com.financeplatform.recurring.entity.RecurringFrequency;
import com.financeplatform.recurring.entity.RecurringTransaction;
import com.financeplatform.recurring.repository.RecurringTransactionRepository;
import com.financeplatform.transaction.dto.TransactionRequest;
import com.financeplatform.transaction.entity.TransactionType;
import com.financeplatform.transaction.service.TransactionService;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class RecurringTransactionService {

    private static final Logger log = LoggerFactory.getLogger(RecurringTransactionService.class);

    private final RecurringTransactionRepository recurringTransactionRepository;
    private final AccountService accountService;
    private final TransactionService transactionService;

    @Transactional(readOnly = true)
    public List<RecurringTransactionResponse> list(UUID userId) {
        return recurringTransactionRepository.findByUserIdOrderByNextOccurrenceDateAsc(userId).stream()
                .map(RecurringTransactionResponse::from)
                .toList();
    }

    @Transactional
    public RecurringTransactionResponse create(RecurringTransactionRequest request, UUID userId) {
        validate(request);
        accountService.findOwned(request.accountId(), userId); // ownership check, discard result
        if (request.type() == TransactionType.TRANSFER) {
            accountService.findOwned(request.transferAccountId(), userId);
        }

        RecurringTransaction rt = RecurringTransaction.builder()
                .userId(userId)
                .accountId(request.accountId())
                .transferAccountId(request.transferAccountId())
                .categoryId(request.categoryId())
                .type(request.type())
                .amount(request.amount())
                .frequency(request.frequency())
                .startDate(request.startDate())
                .nextOccurrenceDate(request.startDate())
                .endDate(request.endDate())
                .description(request.description())
                .merchant(request.merchant())
                .active(request.active() == null || request.active())
                .build();

        return RecurringTransactionResponse.from(recurringTransactionRepository.save(rt));
    }

    @Transactional
    public RecurringTransactionResponse update(UUID id, RecurringTransactionRequest request, UUID userId) {
        validate(request);
        RecurringTransaction rt = findOwned(id, userId);
        accountService.findOwned(request.accountId(), userId);
        if (request.type() == TransactionType.TRANSFER) {
            accountService.findOwned(request.transferAccountId(), userId);
        }

        // Changing startDate restarts the schedule from that date. Leaving
        // it unchanged leaves nextOccurrenceDate exactly where it currently
        // is — editing the amount on a recurring bill shouldn't reset which
        // occurrence is next.
        if (!rt.getStartDate().equals(request.startDate())) {
            rt.setNextOccurrenceDate(request.startDate());
        }

        rt.setAccountId(request.accountId());
        rt.setTransferAccountId(request.transferAccountId());
        rt.setCategoryId(request.categoryId());
        rt.setType(request.type());
        rt.setAmount(request.amount());
        rt.setFrequency(request.frequency());
        rt.setStartDate(request.startDate());
        rt.setEndDate(request.endDate());
        rt.setDescription(request.description());
        rt.setMerchant(request.merchant());
        if (request.active() != null) {
            rt.setActive(request.active());
        }

        return RecurringTransactionResponse.from(recurringTransactionRepository.save(rt));
    }

    @Transactional
    public void delete(UUID id, UUID userId) {
        RecurringTransaction rt = findOwned(id, userId);
        // Hard delete is safe here: generated transactions reference this
        // via recurringTransactionId with ON DELETE SET NULL — they survive,
        // just lose the "auto-generated by" link.
        recurringTransactionRepository.delete(rt);
    }

    /** Called by the nightly scheduler — processes every user's due recurrences. */
    @Transactional
    public int processAllDue(LocalDate asOf) {
        List<RecurringTransaction> due = recurringTransactionRepository
                .findByActiveTrueAndNextOccurrenceDateLessThanEqual(asOf);
        int generated = 0;
        for (RecurringTransaction rt : due) {
            generated += processOne(rt, asOf);
        }
        return generated;
    }

    /** Called by the manual "run due now" endpoint — scoped to one user. */
    @Transactional
    public int processDueForUser(UUID userId, LocalDate asOf) {
        List<RecurringTransaction> due = recurringTransactionRepository
                .findByUserIdAndActiveTrueAndNextOccurrenceDateLessThanEqual(userId, asOf);
        int generated = 0;
        for (RecurringTransaction rt : due) {
            generated += processOne(rt, asOf);
        }
        return generated;
    }

    /**
     * Catches up ALL missed occurrences for one recurring transaction, not
     * just the most recent one — if nextOccurrenceDate is three months
     * behind (app was down, or startDate was set in the past), this creates
     * one real transaction per missed occurrence, in order. For a DAILY
     * recurrence with a startDate set far in the past, that can mean a lot
     * of generated transactions in one run — this is intentional (every
     * occurrence should exist as a real transaction) but worth knowing
     * before setting a startDate you didn't mean literally.
     */
    private int processOne(RecurringTransaction rt, LocalDate asOf) {
        int count = 0;
        try {
            while (rt.isActive()
                    && !rt.getNextOccurrenceDate().isAfter(asOf)
                    && (rt.getEndDate() == null || !rt.getNextOccurrenceDate().isAfter(rt.getEndDate()))) {

                TransactionRequest txRequest = new TransactionRequest(
                        rt.getAccountId(),
                        rt.getTransferAccountId(),
                        rt.getCategoryId(),
                        rt.getType(),
                        rt.getAmount(),
                        rt.getNextOccurrenceDate(),
                        rt.getDescription(),
                        rt.getMerchant()
                );

                transactionService.createFromRecurrence(txRequest, rt.getUserId(), rt.getId());
                count++;

                rt.setNextOccurrenceDate(advance(rt.getNextOccurrenceDate(), rt.getFrequency()));
            }

            if (rt.getEndDate() != null && rt.getNextOccurrenceDate().isAfter(rt.getEndDate())) {
                rt.setActive(false);
            }

            recurringTransactionRepository.save(rt);
        } catch (Exception e) {
            // One broken recurrence (e.g. its account got soft-deleted)
            // must not block every other user's recurring transactions in
            // the same nightly run.
            log.error("Failed to process recurring transaction {}: {}", rt.getId(), e.getMessage(), e);
        }
        return count;
    }

    private LocalDate advance(LocalDate date, RecurringFrequency frequency) {
        return switch (frequency) {
            case DAILY -> date.plusDays(1);
            case WEEKLY -> date.plusWeeks(1);
            case MONTHLY -> date.plusMonths(1);
            case YEARLY -> date.plusYears(1);
        };
    }

    private void validate(RecurringTransactionRequest request) {
        if (request.type() == TransactionType.TRANSFER) {
            if (request.transferAccountId() == null) {
                throw new InvalidRequestException("transferAccountId is required for TRANSFER recurring transactions");
            }
            if (request.transferAccountId().equals(request.accountId())) {
                throw new InvalidRequestException("Cannot transfer an account to itself");
            }
        } else if (request.transferAccountId() != null) {
            throw new InvalidRequestException("transferAccountId must be empty unless type is TRANSFER");
        }
        if (request.endDate() != null && !request.endDate().isAfter(request.startDate())) {
            throw new InvalidRequestException("endDate must be after startDate");
        }
    }

    private RecurringTransaction findOwned(UUID id, UUID userId) {
        return recurringTransactionRepository.findByIdAndUserId(id, userId)
                .orElseThrow(() -> new ResourceNotFoundException("Recurring transaction not found"));
    }
}
